### ISSUE TITLE
安装的时候数据库表怎么创建？数据怎么填充？

### ISSUE THREAD

**Issue by NeilZhong** [Astrian/oa-node.js#1]
文档中创建数据哭的create语句直接到mysql中执行吗？表头字段就用中文？数据库建好后里面没有数据，是不是自己要手动数据几条数据？

**Comment by Astrian** [comment]
@NeilZhong 对，是要自己新建的，没有一键创建脚本

**Comment by Astrian** [comment]
@NeilZhong 创建表之后需要新建第一个初始用户
